Tonconnect fixes
tonkeeper/wallet pull request #176
Opened 2022-12-08 16:58 UTC by bogoslavskiy

2022-12-10 10:47 UTC, sorokin0andrey commented on src/store/zustand/connectedApps/selectors.ts
> +  const connectedApp = state.connectedApps[getChainName()][walletAddress]?.[url];
здесь тоже стоит искать по url.startsWith(app.url)
либо иначе если есть идеи как это лучше сделать

Суть в том, что если приконнектил апп с урлом `https://ton-connect.github.io/demo-dapp`, а потом открыл в браузере урл `https://ton-connect.github.io/demo-dapp?some=query`, то апп не найдется и автоконнект не сработает, поэтому даже перед этим желательно убрать последний слеш у webViewUrl и при добавлении аппа тоже

2022-12-10 10:49 UTC, sorokin0andrey requested changes

2022-12-10 10:49 UTC, sorokin0andrey commented on src/store/zustand/connectedApps/useConnectedAppsStore.ts
>                    ...appData,
здесь стоит убирать последний / чтобы не было проблем с ним

`const url = appData.replace(/\/$/, '')`

2022-12-13 17:38 UTC, sorokin0andrey approved these changes

2022-12-16 16:51 UTC, MariaBit approved these changes

2022-12-16 22:57 UTC, MariaBit approved these changes

2022-12-17 11:23 UTC, merged