feature: new flow
tonkeeper/wallet pull request #262
Opened 2023-03-02 11:02 UTC by bogoslavskiy

2023-03-13 10:09 UTC, sorokin0andrey requested changes

2023-03-13 10:09 UTC, sorokin0andrey commented on packages/mobile/src/uikit/NavBar/NavBar.interface.ts
> +  innerAnimatedStyle?: any
Why any?

2023-03-13 10:09 UTC, sorokin0andrey commented on packages/mobile/src/uikit/Pressable.tsx
> +      // onStartShouldSetResponder={() => true}
needs to remove

2023-03-13 10:09 UTC, sorokin0andrey commented on packages/mobile/src/uikit/Screen/ScreenLagreHeader.tsx
> +            onPress={onPress}
it's better to wrap whole component with memo instead of useMemo

2023-03-13 10:09 UTC, sorokin0andrey commented on packages/mobile/src/uikit/Screen/ScreenScrollList.tsx
> +}
I saw this hook in another file, reuse it

2023-03-13 10:09 UTC, sorokin0andrey commented on packages/mobile/src/uikit/Screen/context/ScreenScrollContext.tsx
> +  // );
needs to remove

2023-03-13 10:09 UTC, sorokin0andrey commented on packages/mobile/src/uikit/StyledNativeCompoenets.ts
> +import {
fix the name of this file "StyledNativeCompoenets.ts" -> "StyledNativeComponents.ts"

2023-03-13 10:25 UTC, bogoslavskiy commented on packages/mobile/src/hooks/useBottomTabBarHeight.tsx
> +}
For reusable screens in modals, because no context outside tab bar

2023-03-13 12:54 UTC, sorokin0andrey approved these changes

2023-03-14 11:57 UTC, voloshinskii approved these changes

2023-03-14 11:58 UTC, merged